service=[
    "नाशिक महानगरपालिका नाशिक तात्पुरते जाहिरातीसाठी निश्चित केलेले जागांचे VIDEO",
"नाशिक शहराचा सर्वकष वाहतुक आराखडा",
"महाराष्ट्र लोकसेवा हक्क अध्यादेश - २०१५",
"हेरिटज वृक्ष अहवाल",
"वृक्ष गणना अहवाल",
"केंद्रीय माहितीचा अधिकार अधिनियम २००५ जनमाहिती अधिकारी व प्रथम अपिलीय अधिकारी यांची माहिती.",
"अंदाज पत्रक २०२४-२५",
"ABHIRUCHI SWARASYA 23-24 EOI",
"ANM अंतिम यादी.",
"Audit report for citilinc 2022 2023",
"Accounts Department",
"Administration",
"Advertisement & License Department",
"Animal Husbandry",
"Audit Department",
"अंतिम प्रभागरचना",
"अंतिम मतदार यादी सार्वत्रिक निवडणूक -२०२२",
"आरक्षण सोडत जाहिर सूचना",
"आरक्षण सोडत नोटीस",
"कर्मचारी निवड समित्यांची इतिवृत्ते",
"कोविड-१९ बाबतची माहिती",
"गणेश उत्सव 2023",
"नगररचना विभागाशी संबंधीत माहिती",
"नाशिक महानगरपालिका प्रारूप प्रभागनिहाय आरक्षण",
"नाशिक शहराचा सर्वकष वाहतुक आराखडा",
"नाशिक शहरात सर्वत्र औषधाची फवारणी",
"पदोन्नती गट 'क' व 'ड'",
"प्रारूप मतदार यादी सार्वत्रिक निवडणूक -२०२२",
"प्रारूप सेवा जेष्ठता यादी 1 Jan 2024",
"फॉर्म डाउनलोड करा",
"मनपा दिवंगत/सेवानिवृत्त् सफाई कामगारांच्या रिक्त् पदी निवड समितीच्या बैठकांचे इतिवृत्त्",
"महाराष्ट्र प्लास्टिक बंदी आदेश",
"मा. आयुक्त सो यांचे अंदाजपत्रकीय निवेदन.",
"मिशन विघ्नहर्ता - 2021",
"विद्युत विभाग",
"विभागनिहाय घंटागाडी निविदा अटीशर्ती",
"सार्वत्रिक निवडणुक 2017 - प्रारुप मतदार यादी",
"सेवाज्येष्ठता बैठकीचे इतिवृत्त",
"सेवाप्रवेश नियम",
"स्थानिक निधी लेखापरीक्षण अहवाल",
"BAMS - NT D LIST",
"BAMS - NTB LIST",
"BAMS - OBC LIST",
"BAMS -NTC LIST",
"BAMS अंतिम यादी.",
"BAMS EWS LIST",
"BAMS MERIT CATEGORY WISE LIST",
"BAMS OPEN SELECTED LIST",
"BAMS OPEN WAITING LIST",
"BAMS SBC LIST",
"BAMS SC LIST",
"BAMS ST LIST",
"BAMS VJ LIST",
"Book Issuing & Printing",
"Budget - 2024-25",
"Covid Testing Centres",
"Centralize Store Department",
"Covid - 19 Updates",
"Covid-19 Updates - 16 May 2021 updated",
"Defaulter Property Tax List",
"Demo",
"Department of Workshops and Establishments,",
"Development Plan and D.C. Rules",
"Disability Section",
"Disaster Management",
"Drainage",
"EOI OF MOBILE TOWER",
"EXPRESSION OF INTEREST FOR LEASE OF TRANSMISSION TOWERS AND TRANSMISSION RECEIVING STATIONS FOR INSTALLATION OF TELECOM EQUIPMENTS.",
"Expression of Interest NUHM/NMC/02/2024",
"Education Department",
"Election 2021",
"Election Department",
"Environment Department",
"Estate",
"Estate Department",
"Event Calender",
"Full Time Medical Officer कंत्राटी पद भरती प्रक्रिया जाहिरात क्र. ०१/२४",
"Feedback",
"FEEDBACKEMal",
"Fire & Disaster Management Department",
"Fire Department Rules & Tariff",
"Garden Department",
"General Administration",
"Godavari Conservation Cell",
"Godavari Conservation Cell",
"Godavari Rejuvenation",
"Hospitals Guidelines for COVID19",
"INVITATION FOR EXPRESSION OF INTEREST FOR THE DEVELOPMENT OF AN I.T. PARK",
"ICMR Portal Data Reporting Forms",
"Important Documents",
"Important Numbers",
"Information Technology Department",
"JNNURM",
"Kamgar Kalyan Department",
"Labor Welfare Department",
"Law Department",
"LBT Department",
"List of Ward wise works - Accounts Dept.",
"Local Body Tax Department",
"MBBS वैद्यकीय अधिकारी अंतिम यादी.",
"Medical Department",
"Memorandum of Agreement",
"Municipal Scretary Department",
"Nashik Climate Action Plan 2024",
"National Clean Air Programme(NCAP)",
"Nashik DCPR - Excluded Part",
"National Clean Air Programme (NCAP)",
"National Hawkers Policy",
"NEW LIBRARY FOR PEOPLE - HT LIBRARY",
"NMC Education",
"NMC Election - 2017",
"NMC Election 2022",
"NMC General Election 2022",
"Old Revised Draft Development Plan For Nashik City",
"PRO Calendar 2024",
"Public Disclosure Law",
"panchayatelection.maharashtra.gov.in",
"Parliamentary Election 2024",
"PIL 176/2012",
"PMAY Survey List - Panchavati",
"Projects Department",
"Public Relation Department",
"Public Works",
"Public Works Department",
"Quality Control Department",
"Quarterly Progress Report",
"Quotation Notice PWD",
"Record Department",
"Records Department",
"Recruitment",
"Registration & Dispatch Department",
"REQUEST FOR PROPOSAL (RFP) for Appointment of PMC",
"Revenue Department",
"Revised Draft Development Plan For Nashik City",
"Right to Information",
"RTI Information of Departments",
"RTS",
"Smart Light Project",
"Secretary & Licenses Department",
"Security Department",
"Seniority List",
"Sewerage",
"Slum",
"Social Media streming Page",
"Social Welfare Department",
"Solid Waste Management",
"Sport",
"Standing Committee",
"Strom Water Drainage",
"Swimming Pool",
"Transferable Development Rights (TDR LIST)",
"Tax Department",
"Test",
"Town Planning",
"Town Planning Department",
"Urban Mobility Cell",
"Vaccination Centers",
"Water Supply (mech.)",
"Water Supply Distribution",
"Women & Child Welfare"]